name: Deploy CI

on:
  push:
    branches:
      - "deploy"

jobs:
  build:
    name: Deploy CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: deploy
          fetch-depth: 0

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        id: build

      - name: Publish package to github
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
        if: steps.build.outcome == 'success'